groups:
- name: NokiaSRLinuxAlerts
  rules:
  - alert: InterfaceDown
    expr: gnmic_srl_if_oper_state == 0
    for: 1m
    labels:
      severity: critical
    annotations:
      description: "Interface has been down for more than 1 minute."
      summary: "Interface down on {{$labels.instance}}"

# groups:
# - name: gnmic_alerts
#   rules:
  
#   # Alert for when an interface goes down
#   - alert: InterfaceDown
#     expr: gnmic_srl_if_oper_state == 0
#     for: 10s
#     labels:
#       severity: critical
#     annotations:
#       summary: "Interface is down"
#       description: "Interface has been down for more than 10 seconds."

#   # Alert for changes in network instance operational state
#   - alert: NetworkInstanceChange
#     expr: changes(gnmic_srl_net_instance[1m]) > 0
#     for: 10s
#     labels:
#       severity: warning
#     annotations:
#       summary: "Network instance state changed"
#       description: "Network instance state has changed in the last minute."

#   # Alert for high CPU usage
#   - alert: HighCpuUsage
#     expr: gnmic_srl_cpu > 70
#     for: 10s
#     labels:
#       severity: critical
#     annotations:
#       summary: "High CPU usage detected"
#       description: "CPU usage is above 70% for more than 10 seconds."

#   # Alert for high memory usage
#   - alert: HighMemoryUsage
#     expr: gnmic_srl_mem > 80
#     for: 10s
#     labels:
#       severity: critical
#     annotations:
#       summary: "High memory usage detected"
#       description: "Memory usage is above 80% for more than 10 seconds."

#   # Alert for changes in BGP session state
#   - alert: BgpSessionChange
#     expr: changes(gnmic_srl_bgp_stats[1m]) > 0
#     for: 10s
#     labels:
#       severity: warning
#     annotations:
#       summary: "BGP session state changed"
#       description: "BGP session state has changed in the last minute."

#   # Alert for a large number of IPv4 routes
#   - alert: HighIpv4Routes
#     expr: gnmic_srl_ipv4_routes > 1000
#     for: 10s
#     labels:
#       severity: warning
#     annotations:
#       summary: "High number of IPv4 routes"
#       description: "Number of IPv4 routes is above 1000 for more than 10 seconds."
