global:
  resolve_timeout: 1m

route:
  receiver: 'dummy-receiver'
  group_by: ['alertname']
  group_wait: 30s
  group_interval: 5m
  repeat_interval: 1h
  routes:
  - match:
      severity: critical

receivers:
- name: 'dummy-receiver'

#   receiver: 'grafana-webhook-receiver'

# receivers:
# - name: 'grafana-webhook-receiver'
#   webhook_configs:
#   - url: 'http://localhost:3000/api/alertmanager/grafana'

#   receiver: 'dummy-receiver'

# receivers:
# - name: 'dummy-receiver'

#receiver not needed once we don't send notifications - not exactly like this
#this way it will be only send to alertmanager to later be shown in Grafana
