global:
  resolve_timeout: 1m

route:
  receiver: 'dummy-receiver'
  group_by: ['alertname']
  group_wait: 30s
  group_interval: 5m
  repeat_interval: 1h
  routes:
  - match:
      severity: critical

receivers:
- name: 'dummy-receiver'
