global:
  scrape_interval: 5s

# alert rule files specifies the alert conditions
rule_files:
  - "alert_rules.yml"

# alertmanager configuration to send alerts
# alerting:
#   alertmanagers:
#   - static_configs:
#     - targets: ["alertmanager:9093"]

# metrics_path defaults to '/metrics'
# scheme defaults to 'http'.
scrape_configs:
  - job_name: "gnmic"
    static_configs:
      - targets: ["gnmic:9273"]
