# Jinja template
---
- name: Full configuration -- interfaces, eBGP and iBGP
  hosts: clab-2pods-spine1
  gather_facts: false
  tasks:
    
    - name: Set p2p interface configuration - spine1
      nokia.srlinux.config:
        update:
          - path: /interface[name=ethernet-1/3]
            value:
              admin-state: enable
              description: "interface description set with Ansible"
          - path: /interface[name=ethernet-1/3]/subinterface[index=0]
            value:
              admin-state: enable
              description: "subinterface description set with Ansible"
          - path: /interface[name=ethernet-1/3]/subinterface[index=0]/ipv4
            value:
              admin-state: enable
          - path: /interface[name=ethernet-1/3]/subinterface[index=0]/ipv4/address[ip-prefix=192.168.11.1/30]
          - path: /network-instance[name=default]/interface[name=ethernet-1/3.0]

      register: set_response_p2p_1

    - debug:
        var: set_response_p2p_1
    
    - name: Set p2p interface configuration - spine1
      nokia.srlinux.config:
        update:
          - path: /interface[name=ethernet-1/1]
            value:
              admin-state: enable
              description: "interface description set with Ansible"
          - path: /interface[name=ethernet-1/1]/subinterface[index=0]
            value:
              admin-state: enable
              description: "subinterface description set with Ansible"
          - path: /interface[name=ethernet-1/1]/subinterface[index=0]/ipv4
            value:
              admin-state: enable
          - path: /interface[name=ethernet-1/1]/subinterface[index=0]/ipv4/address[ip-prefix=192.168.11.10/30]
          - path: /network-instance[name=default]/interface[name=ethernet-1/1.0]

      register: set_response_p2p_2

    - debug:
        var: set_response_p2p_2
    
    - name: Set loopback interface configuration - spine1
      nokia.srlinux.config:
        update:
          - path: /interface[name=system0]
            value:
              admin-state: enable
              description: "interface description set with Ansible"
          - path: /interface[name=system0]/subinterface[index=0]
            value:
              admin-state: enable
              description: "subinterface description set with Ansible"
          - path: /interface[name=system0]/subinterface[index=0]/ipv4
            value:
              admin-state: enable
          - path: /interface[name=system0]/subinterface[index=0]/ipv4/address[ip-prefix=10.0.0.1/32]
          - path: /network-instance[name=default]/interface[name=system0.0]

      register: set_response_loopback

    - debug:
        var: set_response_loopback
    
    - name: Set routing policy - spine1
      nokia.srlinux.config:
        update:
          - path: /routing-policy/policy[name=all]/default-action
            value:
              policy-result: accept

      register: set_response_routing_policy_ebgp

    - debug:
        var: set_response_routing_policy_ebgp
    
    - name: Set protocol eBGP - spine1
      nokia.srlinux.config:
        update:
          - path: /network-instance[name=default]/protocols/bgp
            value:
              admin-state: enable
              autonomous-system: 64514
              router-id: 10.0.0.1
          - path: /network-instance[name=default]/protocols/bgp/group[group-name=eBGP-underlay]  
            value:
              admin-state: enable
              export-policy: all
              import-policy: all
          - path: /network-instance[name=default]/protocols/bgp/afi-safi[afi-safi-name=ipv4-unicast]
            value:
              admin-state: enable
          - path: /network-instance[name=default]/protocols/bgp/neighbor[peer-address=192.168.11.2] 
            value:
              admin-state: enable
              peer-as: 64516
              peer-group: eBGP-underlay
          - path: /network-instance[name=default]/protocols/bgp/neighbor[peer-address=192.168.11.9] 
            value:
              admin-state: enable
              peer-as: 64512
              peer-group: eBGP-underlay
          
      register: set_response_ebgp

    - debug:
        var: set_response_ebgp
    
    - name: Set protocol iBGP - spine1
      nokia.srlinux.config:
        update:
          - path: /network-instance[name=default]/protocols/bgp/group[group-name=iBGP-overlay]
            value:
              admin-state: enable
              export-policy: all
              import-policy: all
          - path: /network-instance[name=default]/protocols/bgp/group[group-name=iBGP-overlay]/afi-safi[afi-safi-name=ipv4-unicast]
            value:
              admin-state: disable
          - path: /network-instance[name=default]/protocols/bgp/group[group-name=iBGP-overlay]/afi-safi[afi-safi-name=evpn]
            value:
              admin-state: enable
          - path: /network-instance[name=default]/protocols/bgp/group[group-name=iBGP-overlay]/local-as
            value:
              as-number: 100
          
          - path: /network-instance[name=default]/protocols/bgp/group[group-name=iBGP-overlay]/route-reflector
            value:
              client: true
              cluster-id: 2.2.2.2
          
          
          - path: /network-instance[name=default]/protocols/bgp/neighbor[peer-address=10.0.0.4] 
            value:
              admin-state: enable
              peer-as: 100
              peer-group: iBGP-overlay
          - path: /network-instance[name=default]/protocols/bgp/neighbor[peer-address=10.0.0.4]/transport
            value:
              local-address: 10.0.0.1
          
      register: set_response_ibgp

    - debug:
        var: set_response_ibgp
    
    
    
    