# Jinja template
---
- name: Full configuration -- interfaces, eBGP and iBGP
  hosts: clab-1pod-spine2
  gather_facts: false
  tasks:
    
    - name: Set p2p interface configuration - spine2
      nokia.srlinux.config:
        update:
          - path: /interface[name=ethernet-1/2]
            value:
              admin-state: enable
              description: "interface description set with Ansible"
          - path: /interface[name=ethernet-1/2]/subinterface[index=0]
            value:
              admin-state: enable
              description: "subinterface description set with Ansible"
          - path: /interface[name=ethernet-1/2]/subinterface[index=0]/ipv4
            value:
              admin-state: enable
          - path: /interface[name=ethernet-1/2]/subinterface[index=0]/ipv4/address[ip-prefix=192.168.11.6/30]
          - path: /network-instance[name=default]/interface[name=ethernet-1/2.0]

      register: set_response_p2p_1

    - debug:
        var: set_response_p2p_1
    
    - name: Set p2p interface configuration - spine2
      nokia.srlinux.config:
        update:
          - path: /interface[name=ethernet-1/1]
            value:
              admin-state: enable
              description: "interface description set with Ansible"
          - path: /interface[name=ethernet-1/1]/subinterface[index=0]
            value:
              admin-state: enable
              description: "subinterface description set with Ansible"
          - path: /interface[name=ethernet-1/1]/subinterface[index=0]/ipv4
            value:
              admin-state: enable
          - path: /interface[name=ethernet-1/1]/subinterface[index=0]/ipv4/address[ip-prefix=192.168.11.10/30]
          - path: /network-instance[name=default]/interface[name=ethernet-1/1.0]

      register: set_response_p2p_2

    - debug:
        var: set_response_p2p_2
    
    - name: Set loopback interface configuration - spine2
      nokia.srlinux.config:
        update:
          - path: /interface[name=system0]
            value:
              admin-state: enable
              description: "interface description set with Ansible"
          - path: /interface[name=system0]/subinterface[index=0]
            value:
              admin-state: enable
              description: "subinterface description set with Ansible"
          - path: /interface[name=system0]/subinterface[index=0]/ipv4
            value:
              admin-state: enable
          - path: /interface[name=system0]/subinterface[index=0]/ipv4/address[ip-prefix=10.0.0.3/32]
          - path: /network-instance[name=default]/interface[name=system0.0]

      register: set_response_loopback

    - debug:
        var: set_response_loopback
    
    - name: Set routing policy - spine2
      nokia.srlinux.config:
        update:
          - path: /routing-policy/policy[name=all]/default-action
            value:
              policy-result: accept

      register: set_response_routing_policy_ebgp

    - debug:
        var: set_response_routing_policy_ebgp
    
    - name: Set protocol eBGP - spine2
      nokia.srlinux.config:
        update:
          - path: /network-instance[name=default]/protocols/bgp
            value:
              admin-state: enable
              autonomous-system: 64514
              router-id: 10.0.0.3
          - path: /network-instance[name=default]/protocols/bgp/group[group-name=eBGP-underlay]  
            value:
              admin-state: enable
              export-policy: all
              import-policy: all
          - path: /network-instance[name=default]/protocols/bgp/afi-safi[afi-safi-name=ipv4-unicast]
            value:
              admin-state: enable
          - path: /network-instance[name=default]/protocols/bgp/neighbor[peer-address=192.168.11.5] 
            value:
              admin-state: enable
              peer-as: 64512
              peer-group: eBGP-underlay
          - path: /network-instance[name=default]/protocols/bgp/neighbor[peer-address=192.168.11.9] 
            value:
              admin-state: enable
              peer-as: 64513
              peer-group: eBGP-underlay
          
      register: set_response_ebgp

    - debug:
        var: set_response_ebgp
    
    
    
    