# Jinja template
---
- name: MAC-VRF configuration
  hosts: clab-test-leaf1
  gather_facts: false
  tasks:
    - name: Set routing policy - leaf1
      nokia.srlinux.config:
        update:
          - path: /routing-policy/policy[name=all]/default-action
            value:
              policy-result: accept

      register: set_response_routing_policy_mac_vrf

    - debug:
        var: set_response_routing_policy_mac_vrf
    
    - name: Set MAC-VRF access interface configuration - leaf1
      nokia.srlinux.config:
        update:
          - path: /interface[name=ethernet-1/1]
            value:
              vlan-tagging: true
          - path: /interface[name=ethernet-1/1]/subinterface[index=0]
            value:
              type: bridged
              admin-state: enable
          - path: /interface[name=ethernet-1/1]/subinterface[index=0]/vlan/encap/untagged

      register: set_response_access_interface_mac_vrf

    - debug:
        var: set_response_access_interface_mac_vrf

    - name: Set MAC-VRF Tunnel/VXLAN interface configuration - leaf1
      nokia.srlinux.config:
        update:
          - path: /tunnel-interface[name=vxlan1]/vxlan-interface[index=1]
            value:
              type: bridged
          - path: /tunnel-interface[name=vxlan1]/vxlan-interface[index=1]/ingress
            value:
              vni: 1

      register: set_response_tunnel_vxlan_interface_mac_vrf

    - debug:
        var: set_response_tunnel_vxlan_interface_mac_vrf
    
    - name: Set MAC-VRF network-instance - leaf1
      nokia.srlinux.config:
        update:
          - path: /network-instance[name=vrf-1]
            value:
              admin-state: enable
              type: mac-vrf
          - path: /network-instance[name=vrf-1]/interface[name=ethernet-1/1.0]
          - path: /network-instance[name=vrf-1]/vxlan-interface[name=vxlan1.1]

          - path: /network-instance[name=vrf-1]/protocols/bgp-evpn/bgp-instance[id=1]
            value:
              admin-state: enable
              vxlan-interface: vxlan1.1
              evi: 111
          - path: /network-instance[name=vrf-1]/protocols/bgp-vpn/bgp-instance[id=1]/route-target
            value:
              export-rt: target:100:111
              import-rt: target:100:111

      register: set_response_network_instance_mac_vrf

    - debug:
        var: set_response_network_instance_mac_vrf