# Jinja template
---
- name: eBGP configuration
  hosts: clab
  gather_facts: false
  tasks:
    - name: Set protocol eBGP - 
      nokia.srlinux.config:
        update:
          - path: /network-instance[name=default]/protocols/bgp
            value:
              admin-state: enable
              autonomous-system: 64513
              router-id: 10.0.0.3/32
              group:
                - group-name: eBGP-underlay
                  admin-state: enable
                  export-policy: all
                  import-policy: all
                  #peer-as: 
                  ipv4-unicast:
                    admin-state: enable
                neighbor:
                  - admin-state: enable
                    peer-address: 
                    peer-as: 
                    peer-group: eBGP-underlay

      register: set_response_ebgp

    - debug:
        var: set_response_ebgp
    
    - name: Set routing policy - 
      nokia.srlinux.config:
        update:
          - path: /routing-policy/policy[name=all]
            value:
              default-action:
                policy-result: accept

      register: set_response

    - debug:
        var: set_response