# Jinja template
---
- name: Add interface
  hosts: clab
  gather_facts: false
  tasks:
    
    - name: Set p2p interface configuration - spine1
      nokia.srlinux.config:
        update:
          - path: /interface[name="ethernet-1/1"]
            value:
              admin-state: enable
              description: "interface description set with Ansible"
              subinterface:
                - index: 0
                  admin-state: enable
                  description: "subinterface description set with Ansible"
                  ipv4:
                    admin-state: enable
                    address:
                      - ip-prefix: "192.168.11.2/30"

      register: set_response_p2p_1

    - debug:
        var: set_response_p2p_1

    - name: Set loopback interface configuration - spine1
      nokia.srlinux.config:
        update:
          - path: /interface[name=system0]
            value:
              admin-state: enable
              description: "interface description set with Ansible"
              subinterface:
                - index: 0
                  admin-state: enable
                  description: "subinterface description set with Ansible"
                  ipv4:
                    admin-state: enable
                    address:
                      - ip-prefix: "10.0.1.1/32"

      register: set_response_loopback_1

    - debug:
        var: set_response_loopback_1
    