# Jinja template
---
- name: iBGP configuration
  hosts: clab-test-spine1
  gather_facts: false
  tasks:
    - name: Set routing policy - spine1
      nokia.srlinux.config:
        update:
          - path: /routing-policy/policy[name=all]/default-action
            value:
              policy-result: accept

      register: set_response_routing_policy_ibgp

    - debug:
        var: set_response_routing_policy_ibgp
    
    - name: Set protocol iBGP - spine1
      nokia.srlinux.config:
        update:
          - path: /network-instance[name=default]/protocols/bgp/group[group-name=iBGP-overlay]  
            value:
              admin-state: enable
              export-policy: all
              import-policy: all
          - path: /network-instance[name=default]/protocols/bgp/afi-safi[afi-safi-name=evpn]
            value:
              admin-state: enable
          - path: /network-instance[name=default]/protocols/bgp/group[group-name=iBGP-overlay]/local-as 
            value:
              as-number: 100
          
          - path: /network-instance[name=default]/protocols/bgp/neighbor[peer-address=10.0.0.1] 
            value:
              admin-state: enable
              peer-as: 100
              peer-group: iBGP-overlay
          - path: /network-instance[name=default]/protocols/bgp/neighbor[peer-address=10.0.0.1]/transport
            value:
              local-address: 10.0.0.2
          
          - path: /network-instance[name=default]/protocols/bgp/neighbor[peer-address=10.0.0.3] 
            value:
              admin-state: enable
              peer-as: 100
              peer-group: iBGP-overlay
          - path: /network-instance[name=default]/protocols/bgp/neighbor[peer-address=10.0.0.3]/transport
            value:
              local-address: 10.0.0.2
          
      register: set_response_ibgp

    - debug:
        var: set_response_ibgp