# Jinja template
---
- name: Add interface
  hosts: clab-test-leaf1
  gather_facts: false
  tasks:
    
    - name: Set p2p interface configuration - leaf1
      nokia.srlinux.config:
        update:
          - path: /interface[name=ethernet-1/49]
            value:
              admin-state: enable
              description: "interface description set with Ansible"
          - path: /interface[name=ethernet-1/49]/subinterface[index=0]
            value:
              admin-state: enable
              description: "subinterface description set with Ansible"
          - path: /interface[name=ethernet-1/49]/subinterface[index=0]/ipv4
            value:
              admin-state: enable
          - path: /interface[name=ethernet-1/49]/subinterface[index=0]/ipv4/address[ip-prefix=192.168.11.1/30]
          - path: /network-instance[name=default]/interface[name=ethernet-1/49.0]

      register: set_response_p2p_1

    - debug:
        var: set_response_p2p_1
    
    - name: Set loopback interface configuration - leaf1
      nokia.srlinux.config:
        update:
          - path: /interface[name=system0]
            value:
              admin-state: enable
              description: "interface description set with Ansible"
          - path: /interface[name=system0]/subinterface[index=0]
            value:
              admin-state: enable
              description: "subinterface description set with Ansible"
          - path: /interface[name=system0]/subinterface[index=0]/ipv4
            value:
              admin-state: enable
          - path: /interface[name=system0]/subinterface[index=0]/ipv4/address[ip-prefix=10.0.0.1/32]
          - path: /network-instance[name=default]/interface[name=system0.0]

      register: set_response_loopback

    - debug:
        var: set_response_loopback