# Jinja template
---
- name: MAC-VRF configuration
  hosts: clab-test-leaf1
  gather_facts: false
  tasks:
    - name: Set routing policy - leaf1
      nokia.srlinux.config:
        update:
          - path: /routing-policy/policy[name=all]/default-action
            value:
              policy-result: accept

      register: set_response_routing_policy_mac-vrf

    - debug:
        var: set_response_routing_policy_mac-vrf
    
    - name: Set MAC-VRF access interface configuration - leaf1
      nokia.srlinux.config:
        update:
          - path: /interface[name=ethernet-1/1]
            value:
              vlan-tagging: true
          - path: /interface[name=ethernet-1/1]/subinterface[index=0]
            value:
              type: bridged
              admin-state: enable
          - path: /interface[name=ethernet-1/1]/subinterface[index=0]/vlan/encap/untagged

      register: set_response_access_interface_mac-vrf

      - debug:
        var: set_response__access_interface_mac-vrf

    - name: Set MAC-VRF Tunnel/VXLAN interface configuration - leaf1
      nokia.srlinux.config:
        update:
          - path: /tunnel-interface[name=vxlanX.X]/vxlan-interface[index=X]
            value:
              type: bridged
          - path: /tunnel-interface[name=vxlanX.X]/vxlan-interface[index=X]/ingress
            value:
              vni: X

      register: set_response_tunnel_vxlan_interface_mac-vrf

      - debug:
        var: set_response_tunnel_vxlan_interface_mac-vrf
    
    - name: Set MAC-VRF network-instance - leaf1
      nokia.srlinux.config:
        update:
          - path: /network-instance[name=vrf-1]/
            value:
              admin-state: enable
              type: mac-vrf
          - path: /network-instance[name=vrf-1]/interface[name=ethernet-1/1.0]
          - path: /network-instance[name=vrf-1]/vxlan-interface[name=vxlanX.X]

          - path: /network-instance[name=vrf-1]/protocols/bgp-evpn/bgp-instance[id=1]
            value:
              admin-state: enable
              vxlan-interface: vxlanX.X
              evi: XXX
          - path: /network-instance[name=vrf-1]/protocols/bgp-vpn/bgp-instance[id=1]/route-target
            value:
              export-rt: target:100:111
              import-rt: target:100:111

      register: set_response_network-instance_mac-vrf

    - debug:
        var: set_response_network-instance_mac-vrf