---
- hosts: localhost
  tasks:

    - name: Execute Python code to generate playbooks
      command: python3 main.py ../inputs/input_2pods.yml general

    - name: Start Containerlab, please wait...
      shell: containerlab deploy --reconfigure -t ../inputs/input_2pods.yml
      become: yes  # This will elevate privileges for this task
      become_method: sudo  # This specifies to use sudo for elevation
    
    - name: Find all generated playbooks
      find:
        paths: ../playbooks
        patterns: "*.yml"
      register: generated_playbooks

    - name: Filter out the inventory file
      set_fact:
        playbook_files: "{{ generated_playbooks.files | rejectattr('path', 'search', 'inventory.yml') | list }}"
    
    - name: Run each generated playbook
      shell: ansible-playbook -i ../playbooks/inventory.yml "{{ item.path }}"
      register: playbook_output
      with_items: "{{ playbook_files }}"

    - debug: 
        msg: "{{ playbook_output }}"


# to run the playbook -- ansible-playbook master_playbook.yml -K
# - K flag is necessary because of sudo privileges need password